version: '3.1'

services:

    nginx:
        image: nginx:alpine
        container_name: nginx
        working_dir: /application
        volumes:
            - .:/srv
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    app:
        container_name: app
        build:
            context: ./docker/php
            args:
                UID: ${UID}
                GID: ${GID}
        volumes:
            - .:/srv
            - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        user: "${UID}:${GID}"

    mysql:
        image: mysql:5.7
        container_name: mysql
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=symfony
            - MYSQL_USER=symfony
            - MYSQL_PASSWORD=symfony
        ports:
            - "3306:3306"

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - "8025:8025"

volumes:
    db:
