version: '3.1'

services:
    app:
        build:
            context: ./docker
            args:
                UID: ${UID}
                GID: ${GID}
        volumes:
            - .:/app
        user: "${UID}:${GID}"
        ports:
            - 80:9000
